#spring:
#  autoconfigure:
#    exclude:
#    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port : 8085
  servlet: 
    context-path: /pedido-service

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://DESKTOP\SQLEXPRESS:1433;DatabaseName=Pedido;SelectMethod=cursor;
    username: sa
    password: spowgate
#    url: jdbc:sqlserver://10.110.1.97;DatabaseName=Pedido;SelectMethod=cursor;
#    username: workflow
#    password: yasworkflow
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 60
      minimum-idle: 20
      pool-name: Pedido
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    properties:
      hibernate: 
        format_sql: true
        ddl-auto: none      
  kafka:
    bootstrap-servers: moped-01.srvs.cloudkafka.com:9094,moped-02.srvs.cloudkafka.com:9094,moped-03.srvs.cloudkafka.com:9094
    properties:
      security: 
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas: 
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="zfclgmlz" password="XIWq1DDVHvdqpkkszTdL4vPPdPaK_lCD";   
    consumer:
      group-id: zfclgmlz-consumers
      auto-offset-reset: latest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json: 
            trusted:
              packages: br.entrega
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
       
cloudkarafka:
  topic: zfclgmlz-default           
